---
abstract: 'Framework for building auto-validating, self-documenting APIs.'
author:
  - 'Ido Perlmuter <ido@ido50.net>'
build_requires:
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300031, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: API-McBain
requires:
  Brannigan: 1.0
  Carp: 0
  Exception::Class: 0
  Getopt::Compact::WithCmd: 0
  Module::Load: 0
  Module::Pluggable: 0
  Term::ANSIColor: 0
  Tie::IxHash: 0
  Try::Tiny: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  homepage: https://github.com/ido50/API-McBain
  repository: https://github.com/ido50/API-McBain.git
version: 0.1
